In [2]:
# TensorFlow es una librería que desarrolló GOOGLE y que nos ayuda a hacer 
# redes neuronales.
# Tensor Flow = Flujo = Operaciones matemáticas de Tensores o Vectores = Matriz
# Vamos a pasar un montón de matrices matemáticas por operaciones para entrenar
# a nuestra red neuroal y generar posteriormete predicciones.
# Vamos a ver los básicos:
# Como generar una gráfica computacional (planos del código) y tipos de datos.

In [3]:
import tensorflow as tf

In [8]:
# El primer tipo de variable que vamos a ver es la constante (no cambia).
# 
#"tf.constant()"
#
# Va a ser un vector de 3 elementos del tipo float y con el nombre ´Constante1´
# Ahora mismo solo estamos definiendo nuestra gráfica computacional.
# Nuestra gráfica, todavía no tiene estos valores predefiinidos.

In [9]:
constante = tf.constant([2.0,3,4], dtype=tf.float32, name='Constante1')

In [10]:
# Por eso si imprimimos "constante" no nos lo hace, solo nos dice que 
# es un tensor, forma 3 (3 elementos) y tipo de dato "float.32".

In [11]:
# El segundo tipo de dato que vamos a ver es el place holder.
#
# "tf.placeholder()"
#
# Es como decirle a nuestro programa que haga una variable que la vamos
# a tener vacía en un inicio pero que la vamos a estar llenando conforme
# avanzamos en nuestro código.
# Normalmente los vamos a usar para nuestros imputs de datos.

In [12]:
apartado = tf.placeholder(tf.float32, name='Apartado1')

In [13]:
# Aquí tampoco nos da un valor definido como en el anterior.

In [14]:
# El siguiente tipo de dato es la variable.
#
# tf.Variable()
#
# Un tipo de dato que nos va a permitir cambiar su valor a lo largo 
# del código.

In [15]:
variable = tf.Variable(3, dtype=tf.float32, name='variable1')

Instructions for updating:
Colocations handled automatically by placer.


In [17]:
print(variable)

<tf.Variable 'variable1:0' shape=() dtype=float32_ref>


In [18]:
# Aquí tampoco nos da un valor definido como en el anterior.

In [19]:
# El siguiente tipo de variable es una matriz que va a rellenar con
# únicamente ceros (0).
#
# "tf.zeros()"
#
# Esto nos va a servir para generar una matriz que posteriormente vamos
# a poder alterar.

In [20]:
matriz = tf.zeros([3,4], tf.int32, name='matriz')

In [21]:
# Esto indica que va a ser una matriz de 3x4, con el tipo de dato entero32,
# cuyo nombre es "matriz".

In [22]:
print(matriz)

Tensor("matriz:0", shape=(3, 4), dtype=int32)


In [23]:
# Aquí tampoco nos da un valor definido como en el anterior.

In [24]:
# Con esto ya tenemos generada la gráfica computacional (planos para el código).
# Vamos a correr la sesion inicializando las variables.

In [25]:
inicializar = tf.global_variables_initializer()

In [27]:
# Esta variable se va a encargar de correr toda nuestra gráfica computacional.

In [26]:
sess = tf.Session()

In [28]:
sess.run(inicializar)

In [29]:
# Al hacer esto ya se ejecutó nuestra gráfica computacional y podemos
# ejecutar todo lo anterior.

In [30]:
print(sess.run(constante))

[2. 3. 4.]


In [31]:
print(sess.run(matriz))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [32]:
print(sess.run(variable))

3.0


In [34]:
# Hacemos una función:

# multiplicacion = float32 * placeholder 

In [38]:
multiplicacion = apartado*constante

In [40]:
# A ese placeholder que definimos arriba, a la hora de correr la multiplicación
# a apartado le voy a asignar un 10, 15, 5.
#
# Constante = 2, 3, 4.
# apartado = 15, 10, 5

In [41]:
print(sess.run(multiplicacion,feed_dict={apartado:[[15,10,5]]}))

[[30. 30. 20.]]


In [42]:
# Ahora vamos a ver como generar multiplicaciones entre matrices y 
# productos punto que es MUY IMPORTANTE y lo vamos a estar usando mucho
# en siguientes apartados.

In [43]:
# Multiplicación de matrices necesita llevar la forma (M,N)x(N,M)=M,M
a = tf.placeholder(tf.float32, shape=(2,2))
b = tf.placeholder(tf.float32, shape=(2,3))
mult = tf.matmul(a,b)
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
print(sess.run(mult,feed_dict={a:[[1,2],[2,2]], b:[[12,21,4],[3,2,4]]}))

[[18. 25. 12.]
 [30. 46. 16.]]


In [44]:
# Explicación:
# Vamos a tener una variable FLOAT "a" del tipo PLACEHOLDER y con forma (2,2)
# Vamos a tener una variable FLOAT "b" del tipo PLACEHOLDER y con forma (2,3)
# Vamos a decirle que a la función multiplicar (a,b) la llame "mult".
# Inicializamos nuestras variables.
# Iniciamos sesión para correr nuestra gráfica computacional.
# Las tres primeras líneas son para definir nuestra gráfica computacional y las
# tres últimas para corrarla.
# Imprimo la ejecución de la función "mult" y como estos eran del tipo PLACEHOLDER
# y no teníamos valores pues los definimos o alimentamos dentro del print.

In [45]:
# Otra operación que también vamos a usar mucho es el producto entre dos
# tensores o vectores.

In [47]:
c = tf.placeholder(tf.float32, shape=(3))
d = tf.placeholder(tf.float32, shape=(3))
punto = tf.tensordot(c,d,1)
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
print(sess.run(punto,feed_dict={c:[1,2,3], d:[3,2,1]}))

10.0


In [46]:
# Explicación:
# Vamos a tener una variable FLOAT "c" del tipo PLACEHOLDER y con forma (3), tres elementos.
# Vamos a tener una variable FLOAT "d" del tipo PLACEHOLDER y con forma (3), tres elementos.
# Establecemos nuestra operación "punto" basada en tensordot (producto entre dos vectores (c,d)).
# Inicializo las variables y lo corro.
# Imprimo la multiplicación y dentro de estas defino el valor de las variables (c,d)